[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
RecurringPayments = "7rX2hvG7Eq2XFAv5WfviYgeyjd2tKoFd4b9i4Ty9ThdS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[idl]
upload = true

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
