[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
RecurringPayments = "DUNyVxYZBG7YvU5Nsbci75stbBnjBtBjjibH6FtVPFaL"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[idl]
upload = true

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize_tuktuk_config = "npx ts-node scripts/initTuktukConfig.ts"
initialize_task_queue = "npx ts-node scripts/initTaskQueue.ts"
add_queue_authority = "npx ts-node scripts/addQueueAuthority.ts"
